"""Initial migration

Revision ID: 7477dd4178c0
Revises: 
Create Date: 2026-06-03 15:39:32.070881

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7477dd4178c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='场景分类表'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像'),
    sa.Column('role', sa.Enum('admin', 'user', 'api', name='user_role'), nullable=False, comment='角色'),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned', name='user_status'), nullable=False),
    sa.Column('quota_daily', sa.Integer(), nullable=False, comment='每日生成配额'),
    sa.Column('quota_used_today', sa.Integer(), nullable=False, comment='今日已用配额'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    comment='用户表'
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_status_role', 'users', ['status', 'role'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='Key 的 SHA256 哈希'),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='Key 前缀，用于展示'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Key 名称'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='权限列表 ["prompt:read", "prompt:write"]'),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='每分钟限制请求数'),
    sa.Column('last_used_at', sa.DateTime(timezone=3), nullable=True, comment='最后使用时间'),
    sa.Column('expires_at', sa.DateTime(timezone=3), nullable=True, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    comment='API Key 表'
    )
    op.create_index('idx_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源 ID'),
    sa.Column('details', sa.JSON(), nullable=True, comment='操作详情'),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='操作审计日志'
    )
    op.create_index('idx_created', 'operation_logs', ['created_at'], unique=False)
    op.create_index('idx_resource', 'operation_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_user_action', 'operation_logs', ['user_id', 'action'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_uuid', sa.String(length=36), nullable=False, comment='业务 UUID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('product_id', sa.String(length=64), nullable=False, comment='产品标识'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='产品名称'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='品牌'),
    sa.Column('material', sa.String(length=200), nullable=True, comment='材质'),
    sa.Column('shape', sa.String(length=200), nullable=True, comment='形状'),
    sa.Column('color', sa.String(length=200), nullable=True, comment='颜色'),
    sa.Column('size', sa.String(length=50), nullable=True, comment='尺寸'),
    sa.Column('lock_tags', sa.Text(), nullable=False, comment='产品外观锁定标签'),
    sa.Column('selling_points', sa.JSON(), nullable=True, comment='核心卖点列表'),
    sa.Column('reference_image', sa.JSON(), nullable=True, comment='参考图说明 {description, angle, lighting}'),
    sa.Column('material_keywords', sa.JSON(), nullable=True, comment='材质关键词列表'),
    sa.Column('brand_tone', sa.String(length=200), nullable=True, comment='品牌调性'),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='product_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_uuid'),
    sa.UniqueConstraint('user_id', 'product_id', name='uk_user_product'),
    comment='产品配置表'
    )
    op.create_index('idx_user_status', 'products', ['user_id', 'status'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_uuid', sa.String(length=36), nullable=False, comment='业务 UUID'),
    sa.Column('scene_id', sa.String(length=64), nullable=False, comment='场景标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='场景名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='场景描述'),
    sa.Column('lighting', sa.Text(), nullable=True, comment='光线描述'),
    sa.Column('background', sa.Text(), nullable=True, comment='背景描述'),
    sa.Column('props', sa.JSON(), nullable=True, comment='道具列表'),
    sa.Column('atmosphere', sa.String(length=200), nullable=True, comment='氛围'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='关键词列表'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类'),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, comment='是否内置场景'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='scene_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['scene_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', name='uk_scene_id'),
    sa.UniqueConstraint('scene_uuid'),
    comment='场景定义表'
    )
    op.create_index('idx_category', 'scenes', ['category_id'], unique=False)
    op.create_index('idx_status_public', 'scenes', ['status', 'is_public'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_uuid', sa.String(length=36), nullable=False, comment='任务 UUID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提交用户'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='关联产品'),
    sa.Column('mode', sa.Enum('template', 'llm', name='generation_mode'), nullable=False, comment='生成模式'),
    sa.Column('scene_ids', sa.JSON(), nullable=False, comment='目标场景 ID 列表'),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'partial', 'completed', 'failed', 'cancelled', name='job_status'), nullable=False, comment='任务状态'),
    sa.Column('total_tasks', sa.Integer(), nullable=False, comment='总子任务数'),
    sa.Column('completed_tasks', sa.Integer(), nullable=False, comment='已完成子任务数'),
    sa.Column('failed_tasks', sa.Integer(), nullable=False, comment='失败子任务数'),
    sa.Column('llm_model', sa.String(length=50), nullable=True, comment='使用的 LLM 模型'),
    sa.Column('llm_temperature', sa.Float(), nullable=False, comment='温度参数'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='额外参数'),
    sa.Column('webhook_url', sa.String(length=500), nullable=True, comment='完成回调 URL'),
    sa.Column('started_at', sa.DateTime(timezone=3), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=3), nullable=True, comment='完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_uuid'),
    comment='生成任务表'
    )
    op.create_index('idx_job_uuid', 'generation_jobs', ['job_uuid'], unique=False)
    op.create_index('idx_status_created', 'generation_jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_user_status', 'generation_jobs', ['user_id', 'status'], unique=False)
    op.create_table('prompt_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='关联产品'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='关联场景'),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False, comment='提示词 SHA256 哈希'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='提示词全文'),
    sa.Column('negative_prompt', sa.Text(), nullable=True, comment='负向提示词'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='参数'),
    sa.Column('generation_count', sa.Integer(), nullable=False, comment='被生成次数'),
    sa.Column('last_used_at', sa.DateTime(timezone=3), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_hash'),
    comment='提示词历史去重表'
    )
    op.create_index('idx_last_used', 'prompt_histories', ['last_used_at'], unique=False)
    op.create_index('idx_user_scene', 'prompt_histories', ['user_id', 'scene_id'], unique=False)
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户 ID'),
    sa.Column('api_key_id', sa.Integer(), nullable=True, comment='API Key ID'),
    sa.Column('endpoint', sa.String(length=200), nullable=False, comment='请求端点'),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False, comment='客户端 IP'),
    sa.Column('result', sa.Enum('allowed', 'blocked', name='rate_limit_result'), nullable=False, comment='限流结果'),
    sa.Column('blocked_reason', sa.String(length=200), nullable=True, comment='拦截原因'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='限流日志'
    )
    op.create_index('idx_ip_time', 'rate_limit_logs', ['client_ip', 'created_at'], unique=False)
    op.create_index('idx_user_time', 'rate_limit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_uuid', sa.String(length=36), nullable=False, comment='业务 UUID'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='关联场景'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('template_type', sa.Enum('system', 'positive', 'negative', 'meta', name='template_type'), nullable=False, comment='模板类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='模板内容（Jinja2）'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='所需变量列表'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认模板'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者'),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='template_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_uuid'),
    comment='提示词模板表'
    )
    op.create_index('idx_scene_type', 'templates', ['scene_id', 'template_type'], unique=False)
    op.create_table('generation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result_uuid', sa.String(length=36), nullable=False, comment='结果 UUID'),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='所属任务'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='关联产品'),
    sa.Column('scene_id', sa.Integer(), nullable=False, comment='关联场景'),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'cached', name='result_status'), nullable=False, comment='子任务状态'),
    sa.Column('mode', sa.Enum('template', 'llm', name='generation_mode'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True, comment='正向提示词'),
    sa.Column('negative_prompt', sa.Text(), nullable=True, comment='负向提示词'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='推荐参数'),
    sa.Column('llm_raw_response', sa.Text(), nullable=True, comment='LLM 原始响应'),
    sa.Column('cache_hit', sa.Boolean(), nullable=False, comment='是否命中缓存'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('started_at', sa.DateTime(timezone=3), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=3), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_uuid'),
    comment='生成结果表'
    )
    op.create_index('idx_job', 'generation_results', ['job_id'], unique=False)
    op.create_index('idx_scene', 'generation_results', ['scene_id'], unique=False)
    op.create_index('idx_status', 'generation_results', ['status'], unique=False)
    op.create_index('idx_user_product', 'generation_results', ['user_id', 'product_id'], unique=False)
    op.create_table('template_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='关联模板'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='该版本内容'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='修改者'),
    sa.Column('change_note', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('created_at', sa.DateTime(timezone=3), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uk_template_version'),
    comment='模板版本历史'
    )
    op.create_index('idx_template_id', 'template_versions', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_template_id', table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index('idx_user_product', table_name='generation_results')
    op.drop_index('idx_status', table_name='generation_results')
    op.drop_index('idx_scene', table_name='generation_results')
    op.drop_index('idx_job', table_name='generation_results')
    op.drop_table('generation_results')
    op.drop_index('idx_scene_type', table_name='templates')
    op.drop_table('templates')
    op.drop_index('idx_user_time', table_name='rate_limit_logs')
    op.drop_index('idx_ip_time', table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    op.drop_index('idx_user_scene', table_name='prompt_histories')
    op.drop_index('idx_last_used', table_name='prompt_histories')
    op.drop_table('prompt_histories')
    op.drop_index('idx_user_status', table_name='generation_jobs')
    op.drop_index('idx_status_created', table_name='generation_jobs')
    op.drop_index('idx_job_uuid', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index('idx_status_public', table_name='scenes')
    op.drop_index('idx_category', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('idx_user_status', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_user_action', table_name='operation_logs')
    op.drop_index('idx_resource', table_name='operation_logs')
    op.drop_index('idx_created', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('idx_user_id', table_name='api_keys')
    op.drop_index('idx_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_status_role', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    op.drop_table('scene_categories')
    # ### end Alembic commands ###
